# Generated by Django 5.1.3 on 2025-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='humidity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
