# Generated by Django 5.1.3 on 2025-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_roomdata_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdata',
            name='humidity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='temperature',
            field=models.FloatField(default=None, null=True),
        ),
    ]
